[package]
name = "dsge_vk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vulkano = "0.27.1"
vulkano-win = "0.27.1"
vulkano-shaders = "0.27.1"
winit = "0.25"
nalgebra = "0.28.0"
spirv-compiler = "0.2.0"
image = "0.23.14"
byteorder = { version = "1.3", default-features = false }

[profile.release.package."*"] # +
opt-level = 3 # +

[profile.release]
opt-level = 3
#opt-level = "3"
lto = true
codegen-units = 1
panic = 'abort'
overflow-checks = false